#!/usr/bin/env bash
# shellcheck shell=bash

BOOT_WAIT_SECONDS="${BOOT_WAIT_SECONDS:-900}"
CHECK_INTERVAL_SECONDS="${CHECK_INTERVAL_SECONDS:-5}"
WAIT_PROGRESS_EVERY_SECONDS="${WAIT_PROGRESS_EVERY_SECONDS:-30}"
POST_RECONCILE_WAIT_SECONDS="${POST_RECONCILE_WAIT_SECONDS:-1800}"
KUBECTL_EXEC_TIMEOUT_SECONDS="${KUBECTL_EXEC_TIMEOUT_SECONDS:-120}"
VAULT_POD_WAIT_SECONDS="${VAULT_POD_WAIT_SECONDS:-1800}"

PUBLIC_URLS="${PUBLIC_URLS:-https://stg.litomi.in/health,https://stg.litomi.in/api/health,https://grafana.litomi.in/}"
SKIP_PUBLIC_CHECK="${SKIP_PUBLIC_CHECK:-false}"

VAULT_NAMESPACE="${VAULT_NAMESPACE:-vault}"
VAULT_POD="${VAULT_POD:-vault-0}"
VAULT_ADDR="${VAULT_ADDR:-https://vault.vault.svc:8200}"
VAULT_CACERT="${VAULT_CACERT:-/vault/userconfig/vault-tls/ca.crt}"
VAULT_TLS_DIR="${VAULT_TLS_DIR:-$HOME/vault-tls}"
VAULT_INIT_OUTPUT="${VAULT_INIT_OUTPUT:-${VAULT_TLS_DIR}/vault-init.json}"
VAULT_SECRETS_DIR="${VAULT_SECRETS_DIR:-${REPO_ROOT}/k8s/vault-secrets}"

SERVICE_NAME="${SERVICE_NAME:-litomi-platform-reboot.service}"
SERVICE_UNIT_PATH="${SERVICE_UNIT_PATH:-/etc/systemd/system/${SERVICE_NAME}}"

KUBECTL_CMD="${KUBECTL_CMD:-}"
FORCE_ARGOCD_BOOTSTRAP_APPLY="${FORCE_ARGOCD_BOOTSTRAP_APPLY:-false}"
K3S_KUBELET_NODE_IP="${K3S_KUBELET_NODE_IP:-}"

SCRIPT_START_EPOCH="$(date +%s)"
OK_COUNT=0
WARN_COUNT=0
