apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat
resources:
  - ../../base/chat
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - digest: sha256:b7189ae42f741c5fe85a4e99aad9c741e53319f3819384f78530e115d6b7cb48
    name: ghcr.io/litomi2026/litomi-chat
