apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat
resources:
  - ../../base/chat
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - digest: sha256:d559980937aa575349ac66342c00715915dad62cb49fef490494897d5ecb1ffa
    name: ghcr.io/litomi2026/litomi-chat
