apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat
resources:
  - ../../base/chat
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - digest: sha256:0f8cd60934557540596c6b76de647375f972689a2e62ce9ae2eb640ae864d588
    name: ghcr.io/litomi2026/litomi-chat
