apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - projects/platform.yaml
  - projects/litomi.yaml

  - applications/vault.yaml
  - applications/external-secrets.yaml
  - applications/metrics-server.yaml
  - applications/cloudflared.yaml
  - applications/gtm-server.yaml
  - applications/monitoring.yaml
  - applications/loki.yaml
  - applications/fluent-bit.yaml
  - applications/tempo.yaml
  - applications/otel-collector.yaml
  - applications/minio-operator.yaml
  - applications/minio.yaml
  - applications/velero.yaml
  - applications/argocd.yaml

  - applications/litomi-stg.yaml
  - applications/litomi-prod.yaml
