apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-worker
resources:
  - ../../base/chat-worker
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-worker-env
    literals:
      - APP_ENV=prod
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:be84af8aebbe4aec981b6af256cc4b50cc230938f299ad1b51ffc109ac13420d
    name: ghcr.io/litomi2026/litomi-chat-worker
