apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-worker
resources:
  - ../../base/chat-worker
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-worker-env
    literals:
      - APP_ENV=prod
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:67fdb89eaad5f1ca55b1b1935d8d46ef4f88a17112ded87d18b0a2798fda728c
    name: ghcr.io/litomi2026/litomi-chat-worker
