apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-worker
resources:
  - ../../base/chat-worker
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-worker-env
    literals:
      - APP_ENV=prod
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:6fc2459f62abce222e8477b548c91cec91b8ff5ebf380ee3494eb45ade6e0c43
    name: ghcr.io/litomi2026/litomi-chat-worker
