apiVersion: v1
kind: Namespace
metadata:
  name: litomi-api
  labels:
    app.kubernetes.io/name: litomi-api
    app.kubernetes.io/part-of: litomi
    gateway.litomi.in/edge-route: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
