installCRDs: true
replicaCount: 1
leaderElect: true
priorityClassName: platform-critical
nodeSelector:
  node-pool-role: platform
tolerations:
  - key: node-pool-role
    operator: Equal
    value: platform
    effect: NoSchedule
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    memory: 128Mi
webhook:
  priorityClassName: platform-critical
  nodeSelector:
    node-pool-role: platform
  tolerations:
    - key: node-pool-role
      operator: Equal
      value: platform
      effect: NoSchedule
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      memory: 64Mi
certController:
  priorityClassName: platform-critical
  nodeSelector:
    node-pool-role: platform
  tolerations:
    - key: node-pool-role
      operator: Equal
      value: platform
      effect: NoSchedule
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi
