apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - configmap-blackbox-exporter.yaml
  - deployment-blackbox-exporter.yaml
  - service-blackbox-exporter.yaml
  - probe-blackbox-public-endpoints.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-grafana-admin.yaml
  - externalsecret-alertmanager-discord-webhook-warning.yaml
  - externalsecret-alertmanager-discord-webhook-critical.yaml
  - alertmanagerconfig-discord.yaml
  - ingress-grafana.yaml
  - servicemonitor-cloudflared.yaml
  - servicemonitor-argocd.yaml
  - prometheusrule-observability-pipeline.yaml
