apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - argocd-metrics
          - argocd-server-metrics
          - argocd-repo-server
          - argocd-applicationset-controller
          - argocd-notifications-controller-metrics
  endpoints:
    - port: metrics
