apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cloudflared
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
