apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns01
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: cloudflare-dns01
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: api-token
      remoteRef:
        key: litomi-prod-cert-manager
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_API_TOKEN
