apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - letsencrypt-cluster-issuer.yaml
patches:
  - path: namespace-patch.yaml
    target:
      version: v1
      kind: Namespace
      name: cert-manager
