crds:
  enabled: true
config:
  enableGatewayAPI: true
extraArgs:
  - --dns01-recursive-nameservers=https://1.1.1.1/dns-query,https://8.8.8.8/dns-query
  - --dns01-recursive-nameservers-only
prometheus:
  enabled: false
global:
  priorityClassName: platform-critical
  nodeSelector:
    node-pool-role: platform
  tolerations:
    - key: node-pool-role
      operator: Equal
      value: platform
      effect: NoSchedule
  leaderElection:
    namespace: cert-manager
replicaCount: 1
resources:
  requests:
    cpu: 20m
    memory: 96Mi
  limits:
    memory: 96Mi
webhook:
  replicaCount: 1
  resources:
    requests:
      cpu: 15m
      memory: 64Mi
    limits:
      memory: 64Mi
cainjector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 96Mi
