apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: platform
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
