apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  url: https://argocd.litomi.in
  users.anonymous.enabled: "false"
  webhook.maxPayloadSizeMB: "10"
  oidc.config: |
    name: Cloudflare Access
    issuer: $oidc.cloudflare.issuer
    clientID: $oidc.cloudflare.clientID
    clientSecret: $oidc.cloudflare.clientSecret
    requestedScopes:
      - openid
      - email
      - profile
      - groups
