apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.cloudflare-cache: |
    url: https://api.cloudflare.com
    headers:
      - name: Authorization
        value: Bearer $cloudflareApiToken
      - name: Content-Type
        value: application/json
  template.cloudflare-cache-purge-litomi-web: |
    webhook:
      cloudflare-cache:
        method: POST
        path: /client/v4/zones/{{ printf "%s" .secrets.cloudflareZoneId }}/purge_cache
        body: |
          {
            "hosts": ["litomi.cc"]
          }
  trigger.on-litomi-web-deployed: |
    - when: >-
        app.metadata.name == 'litomi-web'
        and app.status.sync.status == 'Synced'
        and app.status.health.status == 'Healthy'
        and app.status?.operationState.phase in ['Succeeded']
        and app.status.sync.revision == app.status?.operationState.syncResult.revision
        and one(app.status.operationState.syncResult.resources, {
          .group == 'apps'
          and .kind == 'Deployment'
          and .namespace == 'litomi-web'
          and .name == 'litomi-web'
          and len(.images) == 1
          and .images[0] matches '^ghcr\\.io/litomi2026/litomi-web@sha256:[a-f0-9]{64}$'
        })
      oncePer: >-
        filter(app.status.operationState.syncResult.resources, {
          .group == 'apps'
          and .kind == 'Deployment'
          and .namespace == 'litomi-web'
          and .name == 'litomi-web'
        })[0].images[0]
      send: [cloudflare-cache-purge-litomi-web]
