apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, litomi-argocd-admins, role:admin
    g, litomi-argocd-readonly, role:readonly
  policy.default: role:admin
  scopes: '[groups, email]'
