apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "false"
  url: https://argocd.litomi.in
  users.anonymous.enabled: "false"
  webhook.maxPayloadSizeMB: "10"
  oidc.config: |
    name: Cloudflare Access
    issuer: $argocd-cloudflare-access-oidc:oidc.cloudflare.issuer
    clientID: $argocd-cloudflare-access-oidc:oidc.cloudflare.clientID
    clientSecret: $argocd-cloudflare-access-oidc:oidc.cloudflare.clientSecret
    requestedScopes:
      - openid
      - email
      - profile
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true
    enableUserInfoGroups: true
    userInfoPath: /userinfo
    userInfoCacheExpiration: 5m
