apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-cloudflare-access-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: argocd-cloudflare-access-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: oidc.cloudflare.issuer
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_ACCESS_ARGOCD_ISSUER
    - secretKey: oidc.cloudflare.clientID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_ACCESS_ARGOCD_CLIENT_ID
    - secretKey: oidc.cloudflare.clientSecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: CLOUDFLARE_ACCESS_ARGOCD_CLIENT_SECRET
