apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-ops-repo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: argocd-github-ops-repo
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/litomi2026/litomi-ops.git
        githubAppID: "{{ .githubAppID }}"
        githubAppInstallationID: "{{ .githubAppInstallationID }}"
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
  data:
    - secretKey: githubAppID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: GITHUB_APP_ID
    - secretKey: githubAppInstallationID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: GITHUB_APP_INSTALLATION_ID
    - secretKey: githubAppPrivateKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: GITHUB_APP_PRIVATE_KEY
