apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.11/manifests/install.yaml
  - cloudflare-access-oidc-external-secret.yaml
  - github-webhook-external-secret.yaml
  - argocd-secret-github-webhook-external-secret.yaml
  - route.yaml
patches:
  - path: argocd-cm-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-cmd-params-cm-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: applicationset-controller-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller
  - path: notifications-controller-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-notifications-controller
  - path: redis-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
  - path: repo-server-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
  - path: server-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
  - path: application-controller-patch.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
