apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  template:
    spec:
      priorityClassName: platform-critical
      nodeSelector:
        node-pool-role: platform
      tolerations:
        - key: node-pool-role
          operator: Equal
          value: platform
          effect: NoSchedule
      initContainers:
        - name: secret-init
          securityContext:
            allowPrivilegeEscalation: false
      containers:
        - name: redis
          securityContext:
            allowPrivilegeEscalation: false
