apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-scheduler
  namespace: grafana-k8s-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-k8s-monitoring-scheduler
  namespace: grafana-k8s-monitoring
rules:
  - apiGroups:
      - collectors.grafana.com
    resources:
      - alloys
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-k8s-monitoring-scheduler
  namespace: grafana-k8s-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-k8s-monitoring-scheduler
subjects:
  - kind: ServiceAccount
    name: grafana-k8s-monitoring-scheduler
    namespace: grafana-k8s-monitoring
