apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../project/default
  - ../../project/metrics-server
  - ../../project/platform
  - ../../project/workload
  - metrics-server.yaml
  - platform-argo-rollouts-crds.yaml
  - platform-argo-rollouts.yaml
  - platform-argocd.yaml
  - platform-cert-manager.yaml
  - platform-external-secrets.yaml
  - platform-gateway-api.yaml
  - platform-grafana-k8s-monitoring.yaml
  - platform-istio-base.yaml
  - platform-istio-ingress.yaml
  - platform-istio-system.yaml
  - platform-istiod.yaml
  - platform-priorityclass-platform-critical.yaml
  - platform-priorityclass-platform-standard.yaml
  - platform-priorityclass-workload-standard.yaml
  - platform-storage.yaml
  - workload-litomi-api.yaml
  - workload-litomi-cataloger.yaml
  #   - workload-litomi-chat.yaml
  #   - workload-litomi-chat-push.yaml
  #   - workload-litomi-chat-worker.yaml
  - workload-litomi-web.yaml
