apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litomi-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    notifications.argoproj.io/subscribe.on-litomi-web-deployed.cloudflare-cache: ""
spec:
  project: workload
  source:
    repoURL: https://github.com/litomi2026/litomi-ops.git
    targetRevision: main
    path: k8s/workload/litomi/prod/web
  destination:
    server: https://kubernetes.default.svc
    namespace: litomi-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
