apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litomi-api-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: litomi-api-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: litomi-stg/litomi-backend-secret
