apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litomi
spec:
  ingressClassName: traefik
  rules:
    - host: stg.litomi.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: litomi-api
                port:
                  number: 3002
          - path: /
            pathType: Prefix
            backend:
              service:
                name: litomi-web
                port:
                  number: 3000
    - host: img-stg.litomi.in
      http:
        paths:
          - path: /i
            pathType: Prefix
            backend:
              service:
                name: litomi-api
                port:
                  number: 3002
