apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-stg

resources:
  - ../../base
  - hpa-api.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-api-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-api-google-auth.yaml
  - workload-identity-template/configmap-api-google-credentials.yaml

patches:
  - path: patch-api-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-api-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=stg
      - APP_ORIGIN=https://stg.litomi.in
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.3
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=stg,k8s.cluster.name=litomi-k3s
      - VAPID_PUBLIC_KEY=BCQA2zloAhzL0J3hjB7RTBj9uoG3ZR6elL2kJlrbwZRKw5f4sap5g8AyUsnuDpU49fODsI8icA4o6mu42GmjD3A

replacements:
  - source:
      kind: ConfigMap
      name: litomi-common-env
      fieldPath: data.APP_ORIGIN
    targets:
      - select:
          kind: ConfigMap
          name: litomi-public-env
        fieldPaths:
          - data.NEXT_PUBLIC_APP_ORIGIN
        options:
          create: true

  - source:
      kind: ConfigMap
      name: litomi-common-env
      fieldPath: data.VAPID_PUBLIC_KEY
    targets:
      - select:
          kind: ConfigMap
          name: litomi-public-env
        fieldPaths:
          - data.NEXT_PUBLIC_VAPID_PUBLIC_KEY
        options:
          create: true

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:57fb17809c4dc1afc98e50d23b069865277e99503205382d30199f974a000aad
  - name: litomi-api
    newName: ghcr.io/litomi2026/litomi-api
    digest: sha256:a9f25b785b33baebfbc9c26015540b2ee75c28157d8b98f229f4e038394c4add
