apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litomi-cataloger-env
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: litomi-cataloger-env
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: litomi-prod-cataloger
