apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litomi-prod

resources:
  - ../../base
  # - cataloger-cronjob.yaml
  # - recommender-cronjob.yaml
  - hpa-api.yaml
  - hpa-web.yaml
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-litomi-api-secret.yaml
  - ingress.yaml
  - workload-identity-template/serviceaccount-api-google-auth.yaml
  - workload-identity-template/configmap-api-google-credentials.yaml

patches:
  - path: patch-api-deployment.yaml
  - path: patch-web-deployment.yaml
  - path: workload-identity-template/patch-api-deployment-google-auth.yaml

configMapGenerator:
  - name: litomi-public-env
    envs:
      - public.env.kv

  - name: litomi-common-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.in
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector.tracing.svc:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.01
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment=prod,k8s.cluster.name=litomi-k3s
      - VAPID_PUBLIC_KEY=BCQA2zloAhzL0J3hjB7RTBj9uoG3ZR6elL2kJlrbwZRKw5f4sap5g8AyUsnuDpU49fODsI8icA4o6mu42GmjD3A

replacements:
  - source:
      kind: ConfigMap
      name: litomi-common-env
      fieldPath: data.APP_ORIGIN
    targets:
      - select:
          kind: ConfigMap
          name: litomi-public-env
        fieldPaths:
          - data.NEXT_PUBLIC_APP_ORIGIN
        options:
          create: true

  - source:
      kind: ConfigMap
      name: litomi-common-env
      fieldPath: data.VAPID_PUBLIC_KEY
    targets:
      - select:
          kind: ConfigMap
          name: litomi-public-env
        fieldPaths:
          - data.NEXT_PUBLIC_VAPID_PUBLIC_KEY
        options:
          create: true

images:
  - name: litomi-web
    newName: ghcr.io/litomi2026/litomi-web
    digest: sha256:157d64caff56916d8eaa3601a1a4b48a483c6532ee476240cdccb2c969703e4a
  - name: litomi-api
    newName: ghcr.io/litomi2026/litomi-api
    digest: sha256:eb851eeaac922bd574130453170651f8cc7cea1285ec13af3339d2797cd3c3b5
  - name: litomi-cataloger
    newName: ghcr.io/litomi2026/litomi-cataloger
    digest: sha256:536ba0963cba9167d3171c8a92c75899550a8b47dc7ab14c89f9155171edd2eb
  - name: litomi-recommender
    newName: ghcr.io/litomi2026/litomi-recommender
    digest: sha256:666d05c50bcef66000e52e9dd09b2d00cab871c56d17a702f237227ffecbf3c0
