apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-web
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - canary-service.yaml
  - rollout.yaml
  - route.yaml
  - external-secret.yaml
