apiVersion: v1
kind: Namespace
metadata:
  name: grafana-k8s-monitoring
  labels:
    app.kubernetes.io/name: grafana-k8s-monitoring
    app.kubernetes.io/part-of: platform
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
