apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-cataloger
resources:
  - ../../base/cataloger
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-cataloger
    digest: sha256:c226d0779713d5b5325a919471b007a2acfa710474a0ff1857612a63b2b7d2a6
