apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-cataloger
resources:
  - ../../base/cataloger
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-cataloger
    digest: sha256:dfcc744af3cfd5dd0ef100ce534d6769c356c6e9672523e41d555ce95916c497
