apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-cataloger
resources:
  - ../../base/cataloger
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-cataloger
    digest: sha256:4b25757c592fa9e9a395dc4a8b981f95cebc29f56b1f7db813a21fec77639695
