apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    # Velero node-agent(filesystem backup)는 hostPath + mountPropagation을 사용해요.
    # 그래서 PSA는 별도 namespace에서 privileged로 분리하는 걸 권장해요.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn-version: latest
