installCRDs: true

# Reduce privileges/attack surface: we use namespaced SecretStore + ExternalSecret only.
processClusterStore: false
processClusterExternalSecret: false
processClusterGenerator: false
processClusterPushSecret: false

crds:
  createClusterSecretStore: false
  createClusterExternalSecret: false
  createClusterGenerator: false
  createClusterPushSecret: false

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack

resources:
  requests:
    cpu: 5m
    memory: 160Mi
  limits:
    cpu: 310m
    memory: 192Mi

webhook:
  resources:
    requests:
      cpu: 5m
      memory: 64Mi
    limits:
      cpu: 310m
      memory: 96Mi

certController:
  resources:
    requests:
      cpu: 5m
      memory: 120Mi
    limits:
      cpu: 310m
      memory: 160Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
