apiVersion: v1
kind: ConfigMap
metadata:
  name: litomi-api-google-credentials
data:
  credential-configuration.json: |
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/63417037891/locations/global/workloadIdentityPools/litomi-k3s-pool/providers/litomi-k3s-oidc",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/service-account/token",
        "format": {
          "type": "text"
        }
      },
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/google-analytics-viewer@litomi-2026.iam.gserviceaccount.com:generateAccessToken"
    }
