apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: cloudflared-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared/cloudflared-token
        property: token
