apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-web
resources:
  - ../../base/web
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-web-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment.name=prod,k8s.cluster.name=litomi-prod
      - OTEL_SERVICE_NAME=litomi-web
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.5
images:
  - digest: sha256:1d1c33befb8f107895b3231507284f28df6f345e2b782284c396273cda79c762
    name: ghcr.io/litomi2026/litomi-web
