apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-web
resources:
  - ../../base/web
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-web-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - name: ghcr.io/litomi2026/litomi-web
    digest: sha256:b23e6dff73539e92677dba66a071af676a0e41af9137a0ea8d5c4c5a9a90077c
