apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-web
resources:
  - ../../base/web
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-web-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - digest: sha256:5573f903130d3fd2ce995d0fdb4c41ce34145823ba28d29d6ec39b746514e7c5
    name: ghcr.io/litomi2026/litomi-web
    newName: ghcr.io/litomi2026/litomi-web
