apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    # Keep this annotation in the same Argo CD app as ServersTransport
    # so upstream TLS routing does not break due to cross-owner drift.
    # https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#serverstransport
    traefik.ingress.kubernetes.io/service.serverstransport: argocd-argocd-server-transport@kubernetescrd
