apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-cloudflare-cache-purge-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
    deletionPolicy: Retain
  data:
    - secretKey: cloudflareApiToken
      remoteRef:
        key: argocd/cloudflare-cache-purge-secret
        property: CLOUDFLARE_API_TOKEN
    - secretKey: cloudflareZoneId
      remoteRef:
        key: argocd/cloudflare-cache-purge-secret
        property: CLOUDFLARE_ZONE_ID
