apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.vault.svc:8200
      path: kv
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-argocd
          serviceAccountRef:
            name: eso-vault
            audiences:
              - vault
      caProvider:
        type: ConfigMap
        name: vault-ca
        key: ca.crt
