apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: platform
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
