apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-recommender
resources:
  - ../../base/recommender
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-recommender
    digest: sha256:d46d31bdd94ba8da49c9a6536044105e2557eca5d6a1c99136ee655c28060693
