apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-recommender
resources:
  - ../../base/recommender
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-recommender
    digest: sha256:bbdc25f54680d74378fbdf70c5e6e9ee49da13ecc18689a11eb466da79c07d3f
