apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-recommender
resources:
  - ../../base/recommender
  - limit-range.yaml
  - resource-quota.yaml
images:
  - name: ghcr.io/litomi2026/litomi-recommender
    digest: sha256:c1a6b81406c8b5ab632884cfac3b66dfecea7e1b8c876611c4cc315c48e31ab5
