apiVersion: v1
kind: ResourceQuota
metadata:
  name: budget
spec:
  hard:
    count/configmaps: "4"
    count/secrets: "4"
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
