apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracing

resources:
  - namespace.yaml
  - serviceaccount-eso-vault.yaml
  - secretstore-vault.yaml
  - externalsecret-tempo-minio.yaml
  - networkpolicy-collector-ingress.yaml
  - networkpolicy-tempo-ingress.yaml
