apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
spec:
  description: Cluster add-ons
  sourceRepos:
    - https://github.com/litomi2026/litomi.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://grafana-community.github.io/helm-charts
    - https://fluent.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts
    - https://helm.releases.hashicorp.com
    - https://charts.external-secrets.io
    - https://operator.min.io
    - https://vmware-tanzu.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: cloudflared
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: gtm-server
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: logging
    - server: https://kubernetes.default.svc
      namespace: tracing
    - server: https://kubernetes.default.svc
      namespace: vault
    - server: https://kubernetes.default.svc
      namespace: external-secrets
    - server: https://kubernetes.default.svc
      namespace: minio-operator
    - server: https://kubernetes.default.svc
      namespace: minio
    - server: https://kubernetes.default.svc
      namespace: velero
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: apiregistration.k8s.io
      kind: APIService
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
