apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: loki-minio
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: access_key
      remoteRef:
        key: minio/minio-root
        property: root-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret_key
      remoteRef:
        key: minio/minio-root
        property: root-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
