apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    # Fluent Bit DaemonSet은 node 로그 수집을 위해 hostPath를 사용하므로 restricted/baseline PSA에선 차단돼요.
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn-version: latest
