apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gtm-server
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: platform
  source:
    repoURL: https://github.com/litomi2026/litomi.git
    targetRevision: main
    path: k8s/platform/gtm-server
  destination:
    server: https://kubernetes.default.svc
    namespace: gtm-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
