apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litomi-prod
  annotations:
    argocd.argoproj.io/sync-wave: '4'
    litomi.in/cloudflare-cache-purge-hostname: litomi.in
    notifications.argoproj.io/subscribe.on-litomi-deployed.cloudflare-cache-purge: ''
spec:
  project: litomi
  source:
    repoURL: https://github.com/litomi2026/litomi.git
    targetRevision: main
    path: k8s/apps/litomi/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: litomi-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
