apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-push
resources:
  - ../../base/chat-push
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-push-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:8525c60142cc3933030a59bcb7000d0c48276b20065841fd2e1fb875fb92ea30
    name: ghcr.io/litomi2026/litomi-chat-push
