apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-push
resources:
  - ../../base/chat-push
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-push-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:bd9a9ee363da525a1611861d64b2846b6e08bcbc7884365bec3b46712f934fa3
    name: ghcr.io/litomi2026/litomi-chat-push
