apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-chat-push
resources:
  - ../../base/chat-push
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-chat-push-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
      - APP_POSTGRES_POOL_MAX=1
images:
  - digest: sha256:c94848d5fd43726aa44f37c21474f3b49b928fcee0706e57ba785ae5e0a194df
    name: ghcr.io/litomi2026/litomi-chat-push
