# Declarative Kafka topics. Aiven disables broker-side auto-create, so topics are the
# source of truth for partitions/retention; partitions can only be increased, never
# decreased, and increasing them rehashes key->partition (breaks per-key ordering).
resource "aiven_kafka_topic" "this" {
  for_each = var.topics

  project      = var.project
  service_name = var.service_name
  topic_name   = each.key
  partitions   = each.value.partitions
  replication  = each.value.replication

  config {
    cleanup_policy      = each.value.cleanup_policy
    retention_ms        = tostring(each.value.retention_ms)
    min_insync_replicas = tostring(each.value.min_insync_replicas)
  }
}

# Per-service SASL users. Passwords are generated by Aiven and exposed (sensitive) so
# they can be loaded into the matching app secret. Until an app switches to its user it
# keeps using the avnadmin superuser, which bypasses ACLs.
resource "aiven_kafka_user" "this" {
  for_each = var.users

  project      = var.project
  service_name = var.service_name
  username     = each.value
}

# Least-privilege ACLs. Aiven's simplified ACL model grants the consumer-group access
# implicitly when a topic read is granted, so only topic-scoped grants are needed.
resource "aiven_kafka_acl" "this" {
  for_each = { for a in var.acls : "${a.username}:${a.topic}:${a.permission}" => a }

  project      = var.project
  service_name = var.service_name
  username     = each.value.username
  topic        = each.value.topic
  permission   = each.value.permission
}
