apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-notifier
resources:
  - ../../base/notifier
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-notifier-env
    literals:
      - APP_ORIGIN=https://litomi.cc
images:
  - name: ghcr.io/litomi2026/litomi-notifier
    digest: sha256:1fe797dab32b2205e295be253dd78585f185540da27dd30c43214fe43988580d
