apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-notifier
resources:
  - ../../base/notifier
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-notifier-env
    literals:
      - APP_ORIGIN=https://litomi.cc
images:
  - name: ghcr.io/litomi2026/litomi-notifier
    digest: sha256:a6e848979782160ee008d8420a2e38ddff2619ca2eafa9d54a4e171c292b67b0
