apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-notifier
resources:
  - ../../base/notifier
  - limit-range.yaml
  - resource-quota.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-notifier-env
    literals:
      - APP_ORIGIN=https://litomi.cc
images:
  - name: ghcr.io/litomi2026/litomi-notifier
    digest: sha256:6c49931f9291d05ddeedc498acf5d8488fbe1169b1d6d2ddb8ac1fe39e74c883
