apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-api
resources:
  - ../../base/api
  - hpa.yaml
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
  - rollouts-gatewayapi-rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-api-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
images:
  - digest: sha256:507de0b057c6af438cca89aae464af9692bd1e28c98b82a11df936ee1b253f5c
    name: ghcr.io/litomi2026/litomi-api
    newName: ghcr.io/litomi2026/litomi-api
