apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litomi-api
resources:
  - ../../base/api
  - hpa.yaml
  - pdb.yaml
  - limit-range.yaml
  - resource-quota.yaml
  - rollouts-gatewayapi-rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: litomi-api-env
    literals:
      - APP_ENV=prod
      - APP_ORIGIN=https://litomi.cc
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=litomi,deployment.environment.name=prod,k8s.cluster.name=litomi-prod
      - OTEL_SERVICE_NAME=litomi-api
      - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      - OTEL_TRACES_SAMPLER_ARG=0.5
images:
  - digest: sha256:e52c40ba5f1b8b9af9b3d3d6272e41ddc98ec12c70b855f64cd538dbf0247b65
    name: ghcr.io/litomi2026/litomi-api
