apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    app.kubernetes.io/name: istio-ingress
    app.kubernetes.io/part-of: platform
    gateway.litomi.in/edge-route: "true"
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
