apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gtm-server-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: gtm-server-secret
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: CONTAINER_CONFIG
      remoteRef:
        key: gtm-server/gtm-server-secret
        property: CONTAINER_CONFIG
