apiVersion: v1
kind: Namespace
metadata:
  name: gtm-server
  labels:
    # GTM's official image currently runs as root, so we keep restricted as audit/warn only.
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn-version: latest
